addSbtPlugin("org.playframework" % "sbt-plugin" % "3.0.5")
addSbtPlugin("org.foundweekends.giter8" % "sbt-giter8-scaffold" % "0.16.2")
addSbtPlugin("com.github.sbt" % "sbt-jacoco" % "3.4.0")
addSbtPlugin("com.sonar-scala" % "sbt-sonar" % "2.2.1")
addSbtPlugin("org.scoverage"% "sbt-scoverage" % "2.1.1")
