name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache SBT dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Set up SBT
        uses: olafurpg/setup-scala@v12

      - name: Run tests with Scoverage
        run: sbt clean coverage test coverageReport

      - name: Install SonarQube Scanner
        run: |
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g sonar-scanner

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # Correct secret reference
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}  # Correct secret reference
        run: |
          sonar-scanner \
          -Dsonar.token=sqp_b503e263e344658b0feb1073a102cc778d95ef95 \
          -Dsonar.projectKey=Play_local \
          -Dsonar.sources=app \
          -Dsonar.tests=test \
          -Dsonar.scala.scoverage.reportPath=target/scala-2.13/scoverage-report/scoverage.xml
