name: Run SonarQube with SBT

on: push

jobs:
  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: sbt
      - name: Run SonarQube Analysis
        run: sbt clean compile coverage test coverageReport

      - name: Install SonarQube Scanner
        run: |
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g sonar-scanner

      - name: Run SonarQube Scan
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64  # Ensure JAVA_HOME is set correctly
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        run: |
          sonar-scanner \
          -Dsonar.token=25bddfb75682855adc6e9c52b179f6079b94bd78 \
          -Dproject.settings=sonar-project.properties
