name: Run SonarQube with SBT

on: push

jobs:
  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: sbt
      - name: Run SonarQube Analysis
        run: sbt clean compile coverage test coverageReport
        working-directory: /home/runner/work/Play-sonar/Play-sonar

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dproject.settings=sonar-project.properties
            -Dsonar.scala.coverage.reportPaths=/home/runner/work/Play-sonar/Play-sonar/target/scala-2.13/scoverage-report/scoverage.xml

