name: Run SonarQube with SBT

on: push

jobs:
  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: sbt
          
      - name: Run SonarQube Analysis
        run:  sbt clean compile coverage test coverageReport
      
      - name: Run CustomSonar Action
        uses: Vineet7391/CustomSonar@main
        with: 
           scoverageReport: 'target/scala-2.13/scoverage-report/scoverage.xml'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

          
