name: Run SonarQube with SBT

on: push

jobs:
  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: sbt
      - name: Run SonarQube Analysis
        run: sbt jacoco sonarScan -D"sonar.projectKey=Vineet7391_Play-sonar-" -D"sonar.organization=vineet7391" -D"sonar.host.url=https://sonarcloud.io" -D"sonar.login=${{ secrets.SONAR_TOKAN_LOGIN }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
