name: Run SonarQube with SBT

on: push

jobs:
  sonar_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: sbt

      - name: Run SBT build and tests
        run: sbt clean compile coverage test coverageReport

      - name: Install SonarQube Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          mv sonar-scanner-5.0.1.3006-linux sonar-scanner
          echo "SONAR_SCANNER=$(pwd)/sonar-scanner/bin/sonar-scanner" >> $GITHUB_ENV
          echo "SONAR_PATH=$(pwd)/sonar-scanner/bin" >> $GITHUB_ENV

      - name: Set Java 17 for SonarQube Scanner
        run: |
          export JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
          export PATH="$JAVA_HOME/bin:$PATH"
          java -version  # Verify Java 17 is being used

      - name: Run SonarQube Scanner manually
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.projectBaseDir=${{ github.workspace }}
