name: Run SonarQube with SBT

on: push

jobs:
  sonar_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: sbt
      - name: Run SBT build and tests
        run: sbt clean compile coverage test coverageReport

      - name: SonarQube Scan
        run: sbt clean coverage test sonarScan -D"sonar.login=${{secrets.SONAR_TOKEN}}" -D"sonar.host.url= ${{ secrets.SONAR_HOST_URL }}"
