name: Run SonarQube with SBT

on: push

jobs:
  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: sbt

      - name: Run SonarQube Analysis
        run: sbt clean compile coverage test coverageReport

      - name: Create Directory for Scoverage Report
        run: mkdir -p target/scala-2.13/scoverage-report

      - name: Create Symlink for Scoverage Report
        run: ln -s ${{ github.workspace }}/Play-sonar/target/scala-2.13/scoverage-report/scoverage.xml target/scala-2.13/scoverage-report/scoverage.xml

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: ${{ github.workspace }}/Play-sonar
          args: -Dproject.settings=sonar-project.properties
