name: Run SonarQube with SBT

on: push

jobs:
  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Update Java version to JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: sbt

      - name: Run CustomSonar Action
        uses: Vineet7391/HelloSonar@main
        
      - name: Run SonarQube Analysis
        run: sbt clean compile coverage test coverageReport       
          
      - name: Run CustomSonar Action
        uses: Vineet7391/CustomSonar@main        
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
