name: Run SonarQube with SBT

on: push

jobs:
  sonar_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: sbt
      - name: Ensure workspace directory exists
        run: mkdir -p github/workspace

      - name: Run SonarQube Analysis
        run: |
         cd github/workspace 
         sbt clean compile coverage test coverageReport

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
